"""The order in the car, and the offer measured against it.

    python3 rpi/test_stacking.py

Working two apps at once, a second offer arrives while the first order is still
in the car. The arithmetic behind that lives in advice.js and is checked by
tests/advice.test.js; what is checked here is the part that arithmetic cannot
see — whether the server actually knows an order is being carried, whether it
stops knowing at the right moments, and whether the figure reaches the page.

The destination read off the screen after the accept is checked here for the
same reason, and it is the half of that feature nothing else can see: the
button's only effect is a FILE, and the answer comes back as one more line on a
stdout already carrying readings. Both are only observable from out here.

Driven against the real server with a fake scanner on its stdin contract, so
the mark, the hold and the stream are the real ones. Everything that matters
here is state held across requests, which no unit test of a pure function can
reach.
"""

import io
import json
import os
import socket
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ok = bad = 0


def eq(name, got, want):
    global ok, bad
    if got == want:
        ok += 1
    else:
        bad += 1
        print('FAIL  %s: got %r want %r' % (name, got, want))


def ok_(name, cond):
    eq(name, bool(cond), True)


def skip(why):
    print('%s — skipping the stacking checks' % why)
    sys.exit(0)


def free_port():
    s = socket.socket()
    s.bind(('127.0.0.1', 0))
    port = s.getsockname()[1]
    s.close()
    return port


def get(base, path):
    return json.loads(urllib.request.urlopen(base + path, timeout=5)
                      .read().decode('utf-8'))


def post(base, path, body=None):
    data = json.dumps(body or {}).encode('utf-8')
    req = urllib.request.Request(base + path, data=data, method='POST',
                                 headers={'Content-Type': 'application/json'})
    try:
        return json.loads(urllib.request.urlopen(req, timeout=5)
                          .read().decode('utf-8'))
    except urllib.error.HTTPError as e:
        return json.loads(e.read().decode('utf-8'))


if not (subprocess.call(['node', '--version'], stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL) == 0):
    skip('no node')
if not subprocess.call(['python3', '--version'], stdout=subprocess.DEVNULL,
                       stderr=subprocess.DEVNULL) == 0:
    skip('no python3')

work = tempfile.mkdtemp()

# A scanner that puts one offer on the record, then keeps sending readings of a
# second card for the rest of the run. The second card is what gets measured
# against the first once the first has been marked as taken.
#
# The reading is GENERATED BY THE REAL emit(), not written out here, and that is
# the whole point of this block rather than a tidiness preference.
#
# It used to be a literal, and it carried `target` and `band` — fields the real
# scanner did not send. Advice.stack takes the target from the reading and falls
# back to ZERO when it is not a number, and `worst >= 0` is true of almost every
# pair, so on the actual rig the stack line was painted GREEN, "take both", for
# pairs that lose money against simply finishing the order already in the car.
# This suite passed the whole time, because the fixture supplied the very field
# whose absence was the defect. The same literal never noticed that `dropoff`
# was missing either, so sameArea() was asked about undefined on every real
# reading and `ends` and `route` were permanently null — the town rule, the ZIP
# rule and the map link had never once fired in a car.
#
# A hand-written fixture can drift from the program it stands in for. This
# cannot: if a field the server needs stops being emitted, the end-to-end
# assertions below go wrong, which is exactly what should have happened.
#
# Which offer is on the record is driven from a file the test writes, so the
# sequence is deterministic rather than a race against a sleep. Several of the
# properties below are about what happens when the offer on screen is no longer
# the one in the car, and that cannot be reached at all with a scanner that only
# ever names one.
QUEUE = os.path.join(work, 'next')
# ...and the destination read off the screen AFTER the accept, on its own queue.
# Separate from QUEUE because it is a different message on the same stdout and
# the server tells them apart by shape - see the dropoff block far below.
DROP = os.path.join(work, 'drop')
# ...and a way to make the scanner stop sending READINGS while still answering
# the two queues above. A reading goes through withStack(), which asks
# holding() - so a live scanner expires a carried order within 200ms of its
# time running out, and every path that reads `scanner.holding` raw looks
# identical to one that asks properly. The case where they differ is a scanner
# that has gone silent, which is exactly what this file cannot otherwise stage.
QUIET = os.path.join(work, 'quiet')

# The card the second reading is of, put through the real parser, the real
# rate() and the real emit(). $9.00 over 20 minutes is $27/hr gross and
# $21.60 net at 30c a mile, against a $25 target - deliberately BELOW the line,
# so a stack line that comes back green is saying something false.
sys.path.insert(0, os.path.join(ROOT, 'rpi'))
import offer_parser as _OP                                      # noqa: E402
import scan_pi as _SP                                           # noqa: E402

_CARD = ('$9.00 5 min (1.2 mi) away Chastain Rd NW, Kennesaw '
         '15 min (4.8 mi) trip Canton Rd, Marietta')
_parsed = _OP.parse(_CARD)
_rated = _OP.rate(_parsed, {'target': 25.0, 'band': 15.0, 'costPerMile': 0.3})
_buf, _was = io.StringIO(), sys.stdout
sys.stdout = _buf
try:
    _SP.emit(_rated, _parsed, {'total': 900}, True, whole=True)
finally:
    sys.stdout = _was
READ_PAYLOAD = json.loads(_buf.getvalue().strip())

# Every field Advice.stack() and server.js withStack() read off a reading. Held
# here rather than left implicit, so a field going missing from the wire fails
# with a sentence about what it was for instead of a null two layers away.
# `band` is deliberately NOT in this list. server.js passes it into
# Advice.stack and stack() does not read it - so an assertion that the wire
# carries it would pass for no reason, and a required-fields list with an
# unbreakable entry in it teaches you to trust the whole list less. It is still
# emitted, because the call site asks for it and a payload that does not answer
# its caller is the shape of defect this block exists to catch.
for _need in ('ready', 'pay', 'minutes', 'target', 'costPerMile', 'dropoff',
              # ...and the time the pair is actually measured over. `minutes`
              # is what the CARD printed and is null on every delivery card,
              # where the card states a deadline instead. The held job is
              # stored with its billed time, so timing the new offer off the
              # card compared a shop order against a ride's worth of clock —
              # and timed nothing at all where the card printed no duration.
              # See timedLikeTheHeldJob in server.js.
              'billedMinutes', 'cardMinutes'):
    eq('a real reading carries %s' % _need, _need in READ_PAYLOAD, True)
eq('...with the target the verdict was judged against',
   READ_PAYLOAD['target'], 25.0)
eq('...and where the job ends', READ_PAYLOAD['dropoff'], 'Canton Rd, Marietta')

# The destination line, likewise generated by the real emit_dropoff() rather
# than written out here. Its shape is the whole reason the server can tell it
# from the reading above, which carries a `dropoff` of its own - a cross-street
# off the card, as a STRING. Two meanings on one key in one stream, told apart
# by `.line`, so a fixture that invented either shape would be checking the
# fixture.
_ADDRESS = {'line': '1234 Daffodil Ln, Powder Springs, GA 30127',
            'street': '1234 Daffodil Ln', 'city': 'Powder Springs',
            'state': 'GA', 'zip': '30127'}
_buf, _was = io.StringIO(), sys.stdout
sys.stdout = _buf
try:
    _SP.emit_dropoff(dict(_ADDRESS), ms={'total': 900})
finally:
    sys.stdout = _was
DROP_PAYLOAD = json.loads(_buf.getvalue().strip())
eq('a real destination line carries the address as an object',
   isinstance(DROP_PAYLOAD.get('dropoff'), dict), True)
eq('...with the line the server stores', DROP_PAYLOAD['dropoff'].get('line'),
   _ADDRESS['line'])
eq('...and the reading it must not be confused with carries a string',
   isinstance(READ_PAYLOAD['dropoff'], str), True)

# The other shape of reading, and the one the stack line went silent on.
#
# Uber and DoorDash both state a DEADLINE and no duration, so `minutes` is null
# and the time the verdict was made over is `cardMinutes`. Advice.stack reads
# `offer.minutes` and returns null when it is missing, so the second-job line
# said nothing at all on that whole half of a shift — and said it the same way
# it says "the two jobs are fine together", which is with no line.
#
# Derived from the real payload rather than written out, so a field that stops
# being emitted fails here rather than being quietly absent from the fixture.
DEADLINE_PAYLOAD = dict(READ_PAYLOAD, minutes=None, cardMinutes=34.0,
                        billedMinutes=34.0, fromDeadline=True, deliverBy=1140)
eq('the delivery-card reading states no duration',
   DEADLINE_PAYLOAD['minutes'], None)
eq('...but does state the time the verdict was made over',
   DEADLINE_PAYLOAD['cardMinutes'], 34.0)

DEADLINE = os.path.join(work, 'deadline')

fake = os.path.join(work, 'fakescan.py')
with open(fake, 'w') as fh:
    fh.write(
        'import json, os, time\n'
        'QUEUE = %r\n'
        'DROP = %r\n'
        'QUIET = %r\n'
        'DEADLINE = %r\n'
        'LATE = %r\n'
        'READ = %r\n'
        'DROPPED = %r\n'
        'sent = dropped = None\n'
        'while True:\n'
        '    try:\n'
        '        want = open(QUEUE).read().strip()\n'
        '    except Exception:\n'
        '        want = ""\n'
        '    if want and want != sent:\n'
        '        sent = want\n'
        '        print(json.dumps({"offer": json.loads(want)}), flush=True)\n'
        '    try:\n'
        '        ask = open(DROP).read().strip()\n'
        '    except Exception:\n'
        '        ask = ""\n'
        '    if ask and ask != dropped:\n'
        '        dropped = ask\n'
        '        print(json.dumps(DROPPED), flush=True)\n'
        '    if not os.path.exists(QUIET):\n'
        '        print(json.dumps(LATE if os.path.exists(DEADLINE) else READ), flush=True)\n'
        '    time.sleep(0.2)\n'
        % (QUEUE, DROP, QUIET, DEADLINE, DEADLINE_PAYLOAD,
           READ_PAYLOAD, DROP_PAYLOAD))


def put_dropoff(tag):
    """Make the scanner say it read a destination, once."""
    tmp = DROP + '.part'
    with open(tmp, 'w') as fh:
        fh.write(tag)
    os.replace(tmp, DROP)


def put_offer(offer):
    """Make this the offer on the record, and wait until the server has it."""
    tmp = QUEUE + '.part'
    with open(tmp, 'w') as fh:
        fh.write(json.dumps(offer))
    os.replace(tmp, QUEUE)
    for _ in range(100):
        on = get(base, '/api/status').get('offer')
        if on and on.get('id') == offer['id']:
            return True
        time.sleep(0.1)
    return False


HELD = {'id': 'held-1', 'pay': 12.0, 'minutes': 30.0, 'billedMinutes': 30.0,
        'miles': 8.0, 'cost': 2.4, 'perHour': 19.2}

port = free_port()
journal = os.path.join(work, 'j.jsonl')
# The requests the web side leaves for the camera side go in this run's OWN
# directory, so a scanner running on the same machine cannot eat one and this
# suite cannot leave one lying for it. It is also how the dropoff button can be
# checked at all: the button's only effect is a file, and the file has to be
# somewhere this test knows to look. See handoffDir() in server.js.
handoff = os.path.join(work, 'handoff')
os.makedirs(handoff)
proc = subprocess.Popen(
    ['node', os.path.join(ROOT, 'server.js')],
    env=dict(os.environ, PORT=str(port), HTTPS_PORT='0', JOURNAL=journal,
             UBERSCAN_HANDOFF_DIR=handoff,
             # No grace, so a carried order can be made to expire inside a test
             # instead of ten minutes from now. Everything else in this file
             # marks orders of 12 to 30 minutes, which still run for 18 to 45
             # minutes of overrun - far longer than this suite lives - so this
             # changes nothing except making the one case reachable.
             HOLD_GRACE_MS='0',
             SCANNER='1', SCANNER_CMD='python3', SCANNER_ARGS=fake),
    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
base = 'http://127.0.0.1:%d' % port


def stream_read(timeout=8.0, live=False):
    """One reading off the live stream, as the driving screen receives it.

    `live` skips the replay a new listener is handed on connect. The two travel
    different paths through the server — the replay is written straight to the
    socket, live readings go through broadcast() — so a test that only ever
    reads the first message checks one of them and believes it has checked both.
    """
    req = urllib.request.Request(base + '/api/events')
    body = urllib.request.urlopen(req, timeout=timeout)
    deadline = time.time() + timeout
    while time.time() < deadline:
        line = body.readline().decode('utf-8', 'replace').strip()
        if not line.startswith('data: '):
            continue
        msg = json.loads(line[6:])
        if msg.get('ready') and not (live and msg.get('replay')):
            body.close()
            return msg
    body.close()
    return None


try:
    for _ in range(120):
        try:
            urllib.request.urlopen(base + '/api/status', timeout=1).read()
            break
        except Exception:
            time.sleep(0.1)
    else:
        raise RuntimeError('the server never came up')

    # The offer has to be on the record before it can be marked.
    ok_('the offer reaches the record', put_offer(HELD))
    status = get(base, '/api/status')
    if not status.get('offer'):
        raise SystemExit(1)

    # --- nothing in the car yet ---------------------------------------------
    eq('nothing is being carried to begin with', status.get('holding'), None)
    first = stream_read()
    ok_('a reading arrives', bool(first))
    eq('...and carries no stacked figure', (first or {}).get('stack'), None)
    eq('...nor an order to stack onto', (first or {}).get('holding'), None)

    # Pressing "dropped off" with nothing in the car is the state the driver
    # wanted, not an error to be told about.
    done = post(base, '/api/delivered')
    eq('putting down nothing still answers ok', done.get('ok'), True)
    eq('...and says there was nothing to put down', done.get('wasHolding'), False)

    # --- take it ------------------------------------------------------------
    marked = post(base, '/api/offers/mark',
                  {'id': 'held-1', 'accepted': True})
    eq('the offer marks as taken', marked.get('ok'), True)
    # ...and the answer says there is now an order in the car. This is the ONLY
    # moment the panel can learn that in time to matter: the driver accepted on
    # the phone, the card is gone from the mount, and the destination is on the
    # screen RIGHT NOW - but no reading is coming, so nothing else will tell it.
    # See the took handler in live.html.
    eq('...and says an order is now being carried', marked.get('holding'), True)

    status = get(base, '/api/status')
    ok_('...and becomes the order in the car', bool(status.get('holding')))
    eq('...with its payout', (status.get('holding') or {}).get('pay'), 12.0)
    eq('...and its time', (status.get('holding') or {}).get('minutes'), 30.0)
    # An age, not a timestamp. Two machines, two clocks — the same rule the rest
    # of this API already follows.
    ok_('...held as an age rather than a timestamp',
        isinstance((status.get('holding') or {}).get('heldMs'), (int, float)))
    ok_('no timestamp leaks out of it',
        'acceptedAt' not in (status.get('holding') or {}))

    # --- and the next offer is measured against it --------------------------
    #
    # A LIVE reading, not the replay a new listener is handed. The two take
    # different paths out of this server and a test reading only the first
    # message checks one of them while believing it has checked both.
    second = stream_read(live=True)
    ok_('a live reading still arrives', bool(second))
    ok_('...and it really is a live one, not the replay',
        second is not None and not second.get('replay'))
    s = (second or {}).get('stack')
    ok_('...now carrying a stacked figure', bool(s))
    if s:
        # 12 - 2.4 = 9.60 for the order in hand, essentially all of it still to
        # come; 9 - 1.8 = 7.20 for the new one.
        ok_('the pair is worth about seventeen dollars', 16.5 < s['pay'] <= 16.8)
        # The bound has to be a bound, in both directions and in the right order.
        ok_('the worst case is the two times added', 49.0 < s['maxMinutes'] <= 50.0)
        ok_('the best case is the longer of the two', 29.0 < s['minMinutes'] <= 30.0)
        ok_('the range runs low to high', s['worst'] <= s['best'])
        # $16.80 over 50 minutes is $20.16; over 30 it is $33.60. The target is
        # $25, so the range straddles it — and a straddle is never green.
        eq('a range straddling the target is amber, not green', s['state'], 'warn')
        # ...and the second reading also says what is being carried, so a panel
        # that missed the mark still knows.
        ok_('the reading names the order being carried', bool(second.get('holding')))

    # --- put it down --------------------------------------------------------
    done = post(base, '/api/delivered')
    eq('the order is put down', done.get('ok'), True)
    eq('...and it says there was one', done.get('wasHolding'), True)
    eq('nothing is carried afterwards', get(base, '/api/status').get('holding'), None)

    third = stream_read()
    eq('...and the next offer is judged on its own again',
       (third or {}).get('stack'), None)

    # --- taking the mark back is not the same as delivering, but it does end
    #     the hold: the driver pressed it twice because they did not take it.
    post(base, '/api/offers/mark', {'id': 'held-1', 'accepted': True})
    ok_('marking again picks it back up', bool(get(base, '/api/status').get('holding')))
    unmarked = post(base, '/api/offers/mark', {'id': 'held-1', 'accepted': False})
    eq('unmarking puts it down', get(base, '/api/status').get('holding'), None)
    # ...and says so in the same breath, so the panel hides the two controls
    # rather than leaving them offering a job that is no longer in the car.
    eq('...and the answer says nothing is being carried',
       unmarked.get('holding'), False)

    # --- the offer on screen is not the order in the car ---------------------
    #
    # The ordinary case, not an odd one: the driver takes a job, drives off, and
    # the next card appears while the first is still in the car. Un-marking THAT
    # one — the usual reason being that they pressed it by mistake — must not
    # put down the order they are actually carrying. Nothing here can be reached
    # with a scanner that only ever names one offer, which is why this file
    # drives which offer is on the record.
    post(base, '/api/offers/mark', {'id': 'held-1', 'accepted': True})
    ok_('the first order is in the car', bool(get(base, '/api/status').get('holding')))
    ok_('a second offer reaches the record',
        put_offer({'id': 'other-2', 'pay': 5.0, 'minutes': 12.0,
                   'billedMinutes': 12.0, 'miles': 2.0, 'cost': 0.6,
                   'perHour': 22.0}))
    post(base, '/api/offers/mark', {'id': 'other-2', 'accepted': False})
    held = get(base, '/api/status').get('holding')
    ok_('un-marking a different offer does not put the carried one down',
        bool(held))
    eq('...and the one still in the car is the one that was taken',
       (held or {}).get('pay'), 12.0)
    post(base, '/api/delivered')

    # --- an order the card gave no time for ----------------------------------
    #
    # There is nothing to measure against: with no duration there is no
    # remaining time, so a stacked figure would be a second job's minutes
    # divided by nothing. It must not be carried at all rather than carried
    # forever — an order that never expires puts a stale job against every
    # offer for the rest of the shift, and gets more wrong the longer it sits.
    ok_('an offer with no stated time reaches the record',
        put_offer({'id': 'timeless-3', 'pay': 9.0, 'minutes': None,
                   'billedMinutes': None, 'miles': 3.0, 'cost': 0.9,
                   'perHour': None}))
    post(base, '/api/offers/mark', {'id': 'timeless-3', 'accepted': True})
    eq('...and is not carried, because there is nothing to measure',
       get(base, '/api/status').get('holding'), None)
    timeless = stream_read(live=True)
    eq('...so no offer is stacked against it',
       (timeless or {}).get('stack'), None)
    post(base, '/api/delivered')

    # --- "read the screen in front of you as a destination" ------------------
    #
    # An offer card does not say where a delivery ends - 106 of this driver's
    # 604 cards print "Customer dropoff" and no address - so the address is on
    # the screen AFTER the accept, and this is the whole path by which it gets
    # onto the order in the car.
    #
    # Neither half of that path had a test. The scanner's own end was checked
    # piece by piece and not as a path (see test_scan_pi.py, where a reviewer
    # replaced the wiring with `pass` and every check still passed); this end -
    # the button, and what the server does with the answer - had nothing at all.
    # The button's only effect is a file, and the answer arrives as one more
    # line on a stdout already carrying readings, so both are only observable
    # from out here.
    drop_file = os.path.join(handoff, 'uberscan-dropoff')
    if os.path.exists(drop_file):
        os.remove(drop_file)
    asked = post(base, '/api/dropoff')
    eq('the button answers', asked.get('ok'), True)
    ok_('...by leaving a request where the scanner looks for one',
        os.path.exists(drop_file))
    # It reports whether there is an order to attach the answer to, which is
    # what lets the page say "nothing is being carried" rather than go quiet.
    eq('...and says nothing is being carried', asked.get('holding'), False)

    # A destination read with no order in the car belongs to no job. Storing it
    # anyway would measure the next offer against wherever the camera happened
    # to be pointing.
    put_dropoff('loose')
    time.sleep(1.0)
    eq('an address read with nothing held attaches to nothing',
       get(base, '/api/status').get('holding'), None)
    ok_('...and does not become the offer on the record',
        (get(base, '/api/status').get('offer') or {}).get('id') != 'loose')
    # Asked of the endpoints that read the slot rather than the question.
    #
    # /api/status answers through holding(), which refuses anything without a
    # positive stated time - so a loose address stored into a fabricated order
    # is INVISIBLE there, and asserting only through status left a mutation
    # alive that made the server invent one. These two read `scanner.holding`,
    # and they are what the driver is actually told.
    eq('...and the button still says there is nothing to attach to',
       post(base, '/api/dropoff').get('holding'), False)
    eq('...and putting down still says there was nothing to put down',
       post(base, '/api/delivered').get('wasHolding'), False)

    # ...and the other order of the same two acts, which nothing covered.
    #
    # The block above scans the destination AFTER the accept. But the ⌖ button
    # works before it too, and that is the ordinary use: an offer card usually
    # prints "Customer dropoff" and no address — 129 of this driver's 272 cards
    # name no destination — so tapping it open while SCREENING is how a driver
    # finds out where a job goes before taking it. The card carried
    # `dropoffScanned`; the object built when it went into the car copied the
    # address and left the flag behind.
    #
    # Not a display detail: recordPairing writes `scanned` into the append-only
    # journal off this field, and the header above it says that field IS the
    # difference the button exists to make. Every pair judged against an order
    # screened this way recorded the wrong answer to the one question it was
    # there to answer, and a journal row cannot be corrected afterwards.
    post(base, '/api/delivered')
    ok_('a card to screen reaches the record',
        put_offer({'id': 'scr-1', 'pay': 14.0, 'minutes': 25.0,
                   'billedMinutes': 25.0, 'miles': 6.0, 'cost': 1.8,
                   'perHour': 29.3}))
    post(base, '/api/dropoff')          # pressed with nothing in the car yet
    # A tag of its own: the fake scanner only speaks when this file's
    # CONTENTS change, so reusing 'held' here would silence the press the
    # block below makes.
    put_dropoff('screened')
    for _ in range(60):
        on = get(base, '/api/status').get('offer') or {}
        if on.get('dropoff'):
            break
        time.sleep(0.1)
    on = get(base, '/api/status').get('offer') or {}
    eq('the destination goes onto the card being screened',
       on.get('dropoff'), '1234 Daffodil Ln, Powder Springs, GA 30127')
    eq('...marked as scanned, because it was', on.get('dropoffScanned'), True)

    post(base, '/api/offers/mark', {'id': 'scr-1', 'accepted': True})
    time.sleep(0.4)
    held = get(base, '/api/status').get('holding') or {}
    eq('...and the address travels into the car with the order',
       held.get('dropoff'), '1234 Daffodil Ln, Powder Springs, GA 30127')
    eq('...still marked as scanned rather than read off the card',
       held.get('dropoffScanned'), True)

    # ...and into the journal, which is the half that cannot be corrected.
    # `scanned` is checked below on a card-derived dropoff and comes out False;
    # until this ran, nothing exercised the True side at all, so the field was
    # pinned in one direction and could have been a constant.
    ok_('an offer arrives while the screened order is in the car',
        put_offer({'id': 'paired-scr', 'pay': 9.0, 'minutes': 20.0,
                   'billedMinutes': 20.0, 'miles': 4.0, 'cost': 1.2,
                   'perHour': 23.4, 'dropoff': 'Chastain Rd NW, Kennesaw',
                   'pickup': 'Wingstop (Acworth)'}))
    time.sleep(0.8)
    _scr = []
    for _line in open(journal):
        _line = _line.strip()
        if not _line:
            continue
        try:
            _r = json.loads(_line)
        except Exception:
            continue
        if _r.get('kind') == 'pair' and _r.get('id') == 'paired-scr':
            _scr.append(_r)
    eq('the pairing against it is written down once', len(_scr), 1)
    if _scr:
        eq('...recording that the held order\'s destination was scanned',
           (_scr[0].get('held') or {}).get('scanned'), True)
        eq('...and the address it scanned',
           (_scr[0].get('held') or {}).get('dropoff'),
           '1234 Daffodil Ln, Powder Springs, GA 30127')
    post(base, '/api/delivered')


    # ...and with an order in the car it goes onto it.
    ok_('an offer to carry reaches the record',
        put_offer({'id': 'nav-4', 'pay': 14.0, 'minutes': 25.0,
                   'billedMinutes': 25.0, 'miles': 6.0, 'cost': 1.8,
                   'perHour': 29.3}))
    post(base, '/api/offers/mark', {'id': 'nav-4', 'accepted': True})
    held = get(base, '/api/status').get('holding')
    ok_('...and is in the car', bool(held))
    # Before the answer arrives, the order has no destination and the panel has
    # to be able to tell that from one it merely has not scanned - which is what
    # dropoffScanned is for.
    eq('...with nowhere to go yet', (held or {}).get('dropoff'), None)
    eq('...and nothing scanned', (held or {}).get('dropoffScanned'), False)

    asked = post(base, '/api/dropoff')
    eq('the button says there is something to attach to',
       asked.get('holding'), True)

    put_dropoff('held')
    for _ in range(60):
        held = get(base, '/api/status').get('holding') or {}
        if held.get('dropoff'):
            break
        time.sleep(0.1)
    eq('the destination goes onto the order in the car',
       held.get('dropoff'), '1234 Daffodil Ln, Powder Springs, GA 30127')
    eq('...marked as scanned rather than taken off a card',
       held.get('dropoffScanned'), True)

    # The collision this shape exists to survive. Every reading on the same
    # stdout carries a `dropoff` of its own - 'Canton Rd, Marietta', a
    # cross-street off the card, as a plain string - and the fake scanner is
    # sending one five times a second. If the server told the two apart by the
    # key rather than by `.line`, the scanned address would be overwritten by a
    # cross-street belonging to a completely different card within 200ms.
    time.sleep(1.0)
    held = get(base, '/api/status').get('holding') or {}
    eq('...and a stream of card-derived dropoffs does not overwrite it',
       held.get('dropoff'), '1234 Daffodil Ln, Powder Springs, GA 30127')
    eq('...nor un-mark it as scanned', held.get('dropoffScanned'), True)
    post(base, '/api/delivered')

    # --- an order that ran out of time, asked four different ways ------------
    #
    # `holding(now)` is the question "is an order being carried RIGHT NOW", and
    # it is not the same as reading `scanner.holding`: an order past its stated
    # time plus half again plus the grace is already gone from the panel and
    # from the stack line. Four places answered it off the raw slot instead -
    # the scanner-read attach, /api/dropoff, /api/delivered, and un-marking -
    # so the driver could be told an order was being carried by three of them
    # while the screen in front of them showed none.
    #
    # It could not be reached before, and that is TWO obstacles, not one. Ten
    # minutes of grace is ten minutes of waiting - HOLD_GRACE_MS='0' above
    # removes that. And a live scanner sends a reading five times a second,
    # every one of which goes through withStack() and so through holding(),
    # which expires the order as a side effect: within 200ms the raw slot is
    # null too and the two ways of asking agree again. So the scanner has to go
    # QUIET, which is also the real-world shape of this - a rig whose camera
    # side has died, with no panel open polling it either.
    open(QUIET, 'w').close()
    time.sleep(0.5)

    # A third of a minute of stated time, so with no grace it runs out two
    # seconds after it is taken - long enough to mark it before it dies.
    ok_('a short order reaches the record',
        put_offer({'id': 'brief-5', 'pay': 8.0, 'minutes': 0.0222,
                   'billedMinutes': 0.0222, 'miles': 1.0, 'cost': 0.3,
                   'perHour': 20.0}))
    post(base, '/api/offers/mark', {'id': 'brief-5', 'accepted': True})
    time.sleep(2.5)

    # ONE ORDER PER QUESTION, and each question asked FIRST. holding() nulls an
    # expired order as a side effect of answering, so the first endpoint that
    # asks it properly hides the difference from every endpoint asked after -
    # which is how the first version of this block passed while three of the
    # four raw-slot readers were still in place.
    eq('an expired order is not something to attach an address to',
       post(base, '/api/dropoff').get('holding'), False)
    post(base, '/api/delivered')

    ok_('a second short order reaches the record',
        put_offer({'id': 'brief-6', 'pay': 8.0, 'minutes': 0.0222,
                   'billedMinutes': 0.0222, 'miles': 1.0, 'cost': 0.3,
                   'perHour': 20.0}))
    post(base, '/api/offers/mark', {'id': 'brief-6', 'accepted': True})
    time.sleep(2.5)
    eq('...and putting an expired order down says there was nothing to put down',
       post(base, '/api/delivered').get('wasHolding'), False)

    os.remove(QUIET)
    time.sleep(0.5)

    # --- the pairing, written down where a shift can be graded from it ------
    #
    # The stack line is the newest thing on this rig and until now it left no
    # trace: a shift driven to test it came back with the offers and the marks
    # and NOTHING about what the panel had advised. "When it said take both,
    # was it right?" could not be asked of the file the shift produced, which
    # makes the shift a test of nothing.
    #
    # One row per offer, written when the offer goes on the record and an order
    # is already in the car.
    ok_('an order to pair against reaches the record',
        put_offer({'id': 'pairheld-7', 'pay': 12.0, 'minutes': 30.0,
                   'billedMinutes': 30.0, 'miles': 8.0, 'cost': 2.4,
                   'perHour': 19.2, 'dropoff': 'Oak Ln, Marietta'}))
    post(base, '/api/offers/mark', {'id': 'pairheld-7', 'accepted': True})
    ok_('...and is in the car', bool(get(base, '/api/status').get('holding')))
    # No target, band or costPerMile on this, and that is the point of the
    # fixture rather than an omission. They are the driver's settings, not
    # properties of a card, and scan_pi.emit_offer() has never sent them — it
    # sends id, pay, minutes, perHour, billedMinutes, miles, cost, dropoff,
    # pickup, doubt, uncosted and nothing else. Supplying them here is the
    # drift this file's own comment at the top warns about, and it hid a real
    # defect for as long as it was here: recordPairing read the three off the
    # OFFER, got undefined, and Advice.stack fell back to a target of zero, so
    # every pair row ever written recorded the panel as having said take it.
    ok_('a second offer arrives while it is',
        put_offer({'id': 'paired-8', 'pay': 9.0, 'minutes': 20.0,
                   'billedMinutes': 20.0, 'miles': 4.0, 'cost': 1.2,
                   'perHour': 23.4, 'dropoff': 'Chastain Rd NW, Kennesaw',
                   'pickup': 'Wingstop (Acworth)'}))
    time.sleep(0.8)

    rows = []
    for line in open(journal):
        line = line.strip()
        if line:
            try:
                rows.append(json.loads(line))
            except Exception:
                pass
    # Selected by id, not "the only one in the file". Earlier in this run an
    # offer arrived while a different order was in the car, and that pairing was
    # written down too - correctly. Asserting on whichever came first read the
    # wrong row and reported the wrong failure.
    pairs = [r for r in rows if r.get('kind') == 'pair' and r.get('id') == 'paired-8']
    eq('the pairing is written down, once for this offer', len(pairs), 1)
    ok_('...and every pairing names the offer it judged',
        all(isinstance(r.get('id'), str) and r['id']
            for r in rows if r.get('kind') == 'pair'))
    if pairs:
        pr = pairs[0]
        eq('...carrying what was already in the car',
           (pr.get('held') or {}).get('pay'), 12.0)
        eq('...and where that one ends',
           (pr.get('held') or {}).get('dropoff'), 'Oak Ln, Marietta')
        # The difference the destination button exists to make. A card-derived
        # dropoff is a cross-street; a scanned one is a full address, and which
        # it was decides how much the geography verdict is worth.
        eq('...and whether that came off a card or off a scan',
           (pr.get('held') or {}).get('scanned'), False)
        eq('...the offer it was judged against',
           (pr.get('offer') or {}).get('pay'), 9.0)
        eq('...and where THAT one ends',
           (pr.get('offer') or {}).get('dropoff'), 'Chastain Rd NW, Kennesaw')
        st = pr.get('stack') or {}
        ok_('...and what the panel actually advised', bool(st))
        for field in ('worst', 'best', 'state'):
            ok_('...including %s, which is what gets graded' % field,
                field in st)
        # The field this row exists for, checked against its VALUE rather than
        # its presence. `state in st` was true the whole time the value was a
        # constant: the row was judged against a target of zero, which every
        # rate clears, so every pairing ever recorded said take it. This pair
        # is deliberately one the panel calls a close call — $12.00 over 30
        # minutes already in the car, a $9.00 over 20 offered against it, at
        # the $25 target the reading carries — so a return to a zero target
        # shows up here as 'go'.
        eq('...and the verdict is the one the driver was shown, not a default',
           st.get('state'), 'warn')
        # ...and the row says it was judged at all, so a reader can tell a
        # graded pairing from one written before the panel had a target to
        # judge against.
        eq('...on a row that says it was judged', pr.get('judged'), True)
        # Held against the live panel, not only against a literal: the same
        # pair, asked of the server the same moment it was recorded.
        #
        # `last.stack`, not `stack`. The first version of this read the top
        # level, where /api/status has never had one, so `_live` was always
        # empty and the `if` around it meant the comparison had never once run
        # — a check that cannot fail, in the check written to verify that a
        # verdict is not a constant. There is no `if` now: an empty answer here
        # is a failure, because this endpoint is supposed to be showing a pair.
        _last = get(base, '/api/status').get('last') or {}
        _live = _last.get('stack') or {}
        ok_('the panel is showing a stack line for this pair (%r)'
            % (sorted(_live)[:4],), bool(_live))
        eq('...and the recorded verdict is the one it is showing',
           st.get('state'), _live.get('state'))
        # Two towns that are genuinely different, so the geography really was
        # asked and really did answer. A pairing that recorded `ends: null`
        # every time would look like data and be none.
        eq('...and the geography verdict it drew', st.get('ends'), 'elsewhere')

    # It must not be mistaken for an offer by anything that walks this file.
    eq('a pairing is not counted as an offer',
       [r.get('id') for r in rows
        if not r.get('kind') and r.get('id') == 'paired-8'], [])
    # ...and it has to survive the trip to the box at home, which is the only
    # machine where a shift gets analysed. A row with an id and no seq is
    # exactly the shape the sync used to drop in silence.
    server_src = open(os.path.join(ROOT, 'server.js')).read()
    ok_('the sync knows how to identify a pairing',
        "row.kind === 'pair'" in server_src)

    # --- and back out again, which is the half that was missing --------------
    #
    # These rows were written from the day the feature existed and read by
    # nothing. A driver could work a shift, be advised a dozen times, and have
    # no way afterwards to see a single one of the answers - so the record was
    # being kept for a reader that did not exist. This is that reader.
    feed = get(base, '/api/journal?days=30')
    out = [p for p in (feed.get('pairs') or []) if p.get('id') == 'paired-8']
    eq('the offers page is handed the pairing', len(out), 1)
    if out:
        p = out[0]
        eq('...with the order that was in the car',
           (p.get('held') or {}).get('pay'), 12.0)
        eq('...the offer judged against it',
           (p.get('offer') or {}).get('pay'), 9.0)
        ok_('...and what the panel said about the two of them',
            bool(p.get('stack')))
    # Unmarked is a third answer and not a "no". A page that read `undefined`
    # as "passed" would report a decision on every offer the driver was too
    # busy driving to mark, and then count it against the advice.
    eq('an unmarked pairing says nothing about what the driver did',
       'accepted' in (out[0] if out else {}), False)
    post(base, '/api/offers/mark', {'id': 'paired-8', 'accepted': True})
    feed = get(base, '/api/journal?days=30')
    out = [p for p in (feed.get('pairs') or []) if p.get('id') == 'paired-8']
    eq('...and once marked, the pairing carries the outcome',
       (out[0] if out else {}).get('accepted'), True)
    # The join has to survive the window's own filters. `pairs` rides on the
    # array `latestPerOffer` returns, and `filter` makes a new array - so a
    # line written below the first filter would hand the page an empty list,
    # which reads as a shift where the rig was never asked.
    ok_('the pairing survives a window that hides offers',
        any(p.get('id') == 'paired-8'
            for p in (get(base, '/api/journal?days=30&hidden=1').get('pairs') or [])))
    eq('...and is still not one of the offers',
       [o.get('id') for o in (feed.get('offers') or [])
        if o.get('id') == 'paired-8' and o.get('kind')], [])
    post(base, '/api/delivered')

    # --- the export, which is how any of this reaches anyone -----------------
    #
    # Nothing checked this. It is the one path by which a shift's readings leave
    # the rig, and every question about the parser is answered from the file it
    # produces — so a column silently missing from it costs a whole shift of
    # evidence and shows up as nothing at all.
    import csv as _csv
    import io as _io
    body = urllib.request.urlopen(base + '/api/journal.csv', timeout=10)
    text = body.read().decode('utf-8')
    reader = _csv.reader(_io.StringIO(text))
    header = next(reader, [])
    ok_('the export has a header', bool(header))
    for column in ('at', 'pay', 'minutes', 'miles', 'perHour', 'state',
                   'places', 'text', 'scans', 'when'):
        ok_('...naming %s' % column, column in header)
    # A card is read several times and the readings differ; the export carries
    # the ones that lost as well as the one that won.
    eq('every frame\'s reading has its own column', header.count('scans'), 1)
    ok_('...and the winning reading keeps its own', 'text' in header)

    # ...and the frames come back OUT as frames.
    #
    # They were joined with " | ", and the frames are OCR of a phone screen:
    # this project's own comments record that the card's icon row and its
    # dividers both arrive as pipes, and trim_place cuts at the first one for
    # exactly that reason. So the column added to make the frames analysable was
    # splitting 19% of its own rows mid-frame - 57 of 296 on the first export
    # that carried it - and the damage was invisible, because a fragment of a
    # card still looks like a card.
    #
    # The reading below is one this rig really produces: a pipe, inside a frame.
    # Asked of the writer rather than of this fixture's rows, which are a
    # scanner replay and need not have reached the journal by the time the
    # export is fetched. What matters is the FORM, and the form is decided in
    # one line of server.js.
    server_src = open(os.path.join(ROOT, 'server.js')).read()
    ok_('the export no longer joins frames with a separator the frames contain',
        "v.join(k === 'scans' ? ' | ' : '; ')" not in server_src)
    ok_('...and writes them as JSON, which cannot collide with their content',
        "k === 'scans' ? JSON.stringify(v)" in server_src)
    # ...and any row that did land round-trips.
    for row in _csv.DictReader(_io.StringIO(text)):
        raw = row.get('scans') or ''
        if not raw.strip():
            continue
        try:
            frames = json.loads(raw)
        except Exception:
            frames = None
        ok_('a row of scans parses back into whole frames',
            isinstance(frames, list) and all(isinstance(f, str) for f in frames))
        break

    # --- the delivery card, which had no second-job line at all --------------
    #
    # Advice.stack reads `offer.minutes`, and a delivery card states a deadline
    # and no duration — so the line returned null and the panel drew nothing,
    # on the whole of that half of a shift. Nothing distinguished it from "the
    # two jobs are fine together", which is also nothing.
    #
    # And where the card DID state a duration, the two sides of the comparison
    # were still different quantities: the held job is stored with its billed
    # time, the new offer arrived with the card's. On a $22.00 shop order
    # billed at 95 minutes against an identical card, the worst case came out
    # $18.86/hr over 95-140 minutes instead of $13.89 over 95-190 — the floor
    # overstated by 36% on the one line that says whether to take a second job.
    # An order back in the car first — earlier stages put one down, and with
    # nothing being carried there is correctly no second-job line to draw.
    ok_('an order to stack onto is on the record', put_offer(HELD))
    post(base, '/api/offers/mark', {'id': 'held-1', 'accepted': True})
    ok_('...and in the car',
        (get(base, '/api/status').get('holding') or {}).get('pay') == 12.0)
    open(DEADLINE, 'w').close()
    _deadline_stack = None
    for _ in range(120):
        _last = get(base, '/api/status').get('last') or {}
        if _last.get('fromDeadline'):
            _deadline_stack = _last.get('stack')
            break
        time.sleep(0.1)
    ok_('the delivery card reached the panel',
        _deadline_stack is not None or _last.get('fromDeadline') is True)
    ok_('...and it gets a second-job line like any other card (%r)'
        % (_deadline_stack if not isinstance(_deadline_stack, dict)
           else {k: _deadline_stack[k] for k in ('state', 'minMinutes', 'maxMinutes')
                 if k in _deadline_stack}),
        isinstance(_deadline_stack, dict))
    if isinstance(_deadline_stack, dict):
        # Timed over the deadline's own minutes, which is what the verdict was
        # made from — not over the null the card printed as a duration.
        ok_('...timed over the minutes the verdict was made from (%r)'
            % _deadline_stack.get('maxMinutes'),
            (_deadline_stack.get('maxMinutes') or 0) >= 34.0)
    os.remove(DEADLINE)

finally:
    proc.terminate()
    try:
        proc.wait(timeout=5)
    except Exception:
        proc.kill()

print()
print('%d passed, %d FAILED' % (ok, bad) if bad
      else 'All %d stacking checks passed' % ok)
sys.exit(1 if bad else 0)
